### ISSUE TITLE
--openstack-image-name=“base_ubuntu_14.04”: command not found

### ISSUE THREAD

**Issue by fermenreq** [fiware-docker/simple-docker-hosting#1]
Hi all ! 

Im trying to **create** a docker host on FIWARE using my **Docker Machine** that it is running on **Fiware Cloud**, and when I execute the command:

`$ docker-machine create -d openstack --openstack-flavor-id="2“ \ 
--openstack-image-name=“base_Ubuntu_14.04” \
--openstack-net-name="node-int-net-01"  \
--openstack-floatingip-pool="public-ext-net-01"  \
--openstack-sec-groups="docker-machine-sg"  \
--openstack-ssh-user=“ubuntu”  \
FIWARE-SPAIN2  `

I get the following **error** : 

`--openstack-image-name=“base_ubuntu_14.04”: command not found
`

My requierements are : 

root@fernandotest:/# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false`
and the OS Ubuntu 14.04

I have the security groups created like the doc said

Best Regards ! 
Fernando Mendez Requena 
fernando.mendez.external@atos.net

**Comment by KennethNagin** [comment]
I think you have a typo.  You should use lowercase, i.e.
Replace --openstack-image-name=?base_Ubuntu_14.04? 
with --openstack-image-name=?base_ubuntu_14.04?

Best Regards,

Kenneth Nagin
Ph: +972-4-8296227
Cell: 054-6976227
Fx: +972-4- 8296114
http://researcher.ibm.com/view.php?person=il-NAGIN

**Comment by fermenreq** [comment]
Hi, good morning

I replaced it and isn't work: 

`root@fernandotest:/# > docker-machine create -d openstack --openstack-flavor-id="2“ \
> Error creating machine: Invalid hostname specified. Allowed hostname chars are: 0-9a-zA-Z . -
> root@fernandotest:/# --openstack-image-name=“base_ubuntu_14.04” \
> --openstack-net-name="node-int-net-01" \
> --openstack-floatingip-pool="public-ext-net-01" \
> --openstack-sec-groups="docker-machine-sg" \
> --openstack-image-name=“base_ubuntu_14.04”: command not found
> --openstack-ssh-user=“ubuntu” \ FIWARE-SPAIN2
`

**Comment by fermenreq** [comment]
Oups Thanks! but If I run: 

`root@fernandotest:/docker-machine create -d openstack --openstack-flavor-id="2“ --openstack-image-name=“base_Ubuntu_14.04” --openstack-net-name="node-int-net-01" --openstack-floatingip-pool="public-ext-net-01" --openstack-sec-groups="docker-machine-sg" --openstack-ssh-user=“ubuntu” \ FIWARE-SPAIN2`

**Error creating machine: Invalid hostname specified. Allowed hostname chars are: 0-9a-zA-Z . -**

and if I try this command:

`root@fernandotest:/#docker-machine create -d openstack --openstack-flavor-id="2“ --openstack-image-name=“base_Ubuntu_14.04” --openstack-net-name="node-int-net-01" --openstack-floatingip-pool="public-ext-net-01" --openstack-sec-groups="docker-machine-sg" --openstack-ssh-user=“ubuntu” FIWARE-SPAIN2
`

**Error setting machine configuration from flags provided: Authentication URL must be specified either using the environment variable OS_AUTH_URL or the CLI option --openstack-auth-url**


Thanks in advanced !

**Comment by glikson** [comment]
Have you specified environment variables, as explained in the manual?
http://simple-docker-hosting-on-fiware-cloud.readthedocs.io/en/v1.0/manuals/install/

**Comment by fermenreq** [comment]
Hi @glikson 

Thanks for your reply! Yes, its created with my settings 

When I execute the following comand:


`root@manager:/# >docker-machine create -d openstack
--openstack-image-name="base_ubuntu_14.04"
--openstack-net-name="node-int-net-01"
--openstack-floatingip-pool="public-ext-net-01"
`

I get the following error : 

`
No command 'create' found, did you mean:
 Command 'pcreate' from package 'python-pyramid' (universe)
 Command 'pcreate' from package 'pbuilder-scripts' (universe)
create: command not found
--openstack-sec-groups="docker-machine-sg" docker-hostroot@manager:/# --openstack-flavor-id="2"
--openstack-flavor-id=2: command not found
root@manager:/# --openstack-image-name="base_ubuntu_14.04"
--openstack-image-name=base_ubuntu_14.04: command not found
root@manager:/# --openstack-net-name="node-int-net-01"
--openstack-net-name=node-int-net-01: command not found
root@manager:/# --openstack-floatingip-pool="public-ext-net-01"
--openstack-floatingip-pool=public-ext-net-01: command not found
`

Im seeing the docs here: [http://simple-docker-hosting-on-fiware-cloud.readthedocs.io/en/v1.0/manuals/install/#installing-docker-on-fiware-cloud](http://simple-docker-hosting-on-fiware-cloud.readthedocs.io/en/v1.0/manuals/install/#installing-docker-on-fiware-cloud)

and here [https://github.com/fiware-docker/simple-docker-hosting/blob/master/doc/manuals/install.md](https://github.com/fiware-docker/simple-docker-hosting/blob/master/doc/manuals/install.md)


I notice that Im using the lastest version of Docker:

root@manager:/# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@manager:/#

and the simple docker hosting on fiware cloud version is v.1.0
